Repository woocommerce/woocommerce-google-analytics-integration, pull requests merged in 2022-11, with the labels that each got.

#235 Add Google Analytics into Things to do next list
  includes/class-wc-google-analytics-task.php
  includes/class-wc-google-analytics.php
  woocommerce-google-analytics-integration.php
Labels: type: enhancement, changelog: add

#238 Add .nvmrc file
  .nvmrc
Labels: type: compatibility, changelog: dev

#230 Fix inconsistencies across item data in events
  assets/js/ga-integration.js
  includes/class-wc-abstract-google-analytics-js.php
  includes/class-wc-google-analytics.php
  includes/class-wc-google-gtag-js.php
Labels: type: bug, changelog: fix
