Repository woocommerce/woocommerce-google-analytics-integration, pull requests merged in 2023-11, with the labels that each got.

#311 Update tracking for blocks
  assets/js/src/actions.js
  assets/js/src/tracking.js
  assets/js/src/utils.js
Labels: changelog: update

#325 Update docs domain name to Woo.com
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  README.md
  includes/class-wc-google-analytics.php
  woocommerce-google-analytics-integration.php
Labels: changelog: update

#333 Update phpunit polyfills to 1.1
  composer.json
  composer.lock
Labels: changelog: tweak

#331 Add a new workflow of GitHub Actions to publish the latest extension build for the `trunk` branch
  .github/workflows/build.yml
  README.md
Labels: changelog: dev

#332 Prevent firing up the add_to_cart event when clicking in product image
  includes/class-wc-google-analytics-js.php
  includes/class-wc-google-gtag-js.php
Labels: type: bug, changelog: fix

#336 Add missing semicolon to the gtag call
  includes/class-wc-google-gtag-js.php
Labels: type: bug, changelog: fix

#335 Update test environment setup to resolve notice
  tests/class-unittestsbootstrap.php
Labels: type: bug, changelog: fix
