Repository woocommerce/woocommerce-google-analytics-integration, pull requests merged in 2023-01, with the labels that each got.

#242 Fix undefined constant WC warning and bump WC compatibilty version
  woocommerce-google-analytics-integration.php
Labels: type: bug, changelog: fix

#240 Add common events method
  includes/class-wc-google-analytics.php
  includes/class-wc-google-gtag-js.php
Labels: type: technical debt, changelog: dev

#246 Fix usage of tracker_var() in load_analytics()
  includes/class-wc-google-gtag-js.php
Labels: priority: low, type: bug, changelog: fix

#245 Add PHP unit tests
  README.md
  bin/install-unit-tests.sh
  bin/switch-wp-wc-in-unit-tests.sh
  bin/unit-tests-functions.sh
  composer.json
  composer.lock
  includes/class-wc-abstract-google-analytics-js.php
  includes/class-wc-google-gtag-js.php
  phpunit.xml.dist
  tests/EventsDataTest.php
  tests/bootstrap.php
  tests/class-unittestsbootstrap.php
  tests/unit-tests/AddTransactionEnhanced.php
  tests/unit-tests/CheckoutProcess.php
  tests/unit-tests/ListingClick.php
  tests/unit-tests/ListingImpression.php
  tests/unit-tests/ProductDetail.php
Labels: type: enhancement, changelog: add

#249 Feature/consistency across gtag implementation
  README.md
  assets/js/ga-integration.js
  bin/install-unit-tests.sh
  bin/switch-wp-wc-in-unit-tests.sh
  bin/unit-tests-functions.sh
  composer.json
  composer.lock
  includes/class-wc-abstract-google-analytics-js.php
  includes/class-wc-google-analytics.php
  includes/class-wc-google-gtag-js.php
  phpunit.xml.dist
  tests/EventsDataTest.php
  tests/bootstrap.php
  tests/class-unittestsbootstrap.php
  tests/unit-tests/AddTransactionEnhanced.php
  tests/unit-tests/CheckoutProcess.php
  tests/unit-tests/ListingClick.php
  tests/unit-tests/ListingImpression.php
  tests/unit-tests/ProductDetail.php
Labels: type: enhancement, changelog: update
