Repository woocommerce/woocommerce-google-analytics-integration, pull requests merged in 2023-10, with the labels that each got.

#307 Enable since tag replacement
  includes/class-wc-google-analytics.php
  includes/class-wc-google-gtag-js.php
  package.json
  tests/EventsDataTest.php
  tests/unit-tests/AddTransactionEnhanced.php
  tests/unit-tests/CheckoutProcess.php
  tests/unit-tests/ListingClick.php
  tests/unit-tests/ListingImpression.php
  tests/unit-tests/ProductDetail.php
  tests/unit-tests/WCGoogleGtagJS.php
  woocommerce-google-analytics-integration.php
Labels: changelog: dev

#310 Wrap inline `remove_from_cart` script in IIFE
  includes/class-wc-google-gtag-js.php
Labels: type: bug, changelog: fix

#309 Add product identifier setting
  includes/class-wc-abstract-google-analytics-js.php
  includes/class-wc-google-analytics.php
  tests/unit-tests/WCGoogleGtagJS.php
  woocommerce-google-analytics-integration.php
Labels: type: enhancement, changelog: add

#316 Declare Compatibility for cart_checkout_blocks
  woocommerce-google-analytics-integration.php
Labels: changelog: tweak

#323 Update WordPressCS to version 3.0
  composer.json
  composer.lock
  includes/class-wc-google-analytics-js.php
  includes/class-wc-google-analytics-task.php
  includes/class-wc-google-analytics.php
  includes/class-wc-google-gtag-js.php
  phpcs.xml.dist
  tests/EventsDataTest.php
  tests/class-unittestsbootstrap.php
  tests/unit-tests/AddTransactionEnhanced.php
  tests/unit-tests/CheckoutProcess.php
  tests/unit-tests/ListingClick.php
  tests/unit-tests/ListingImpression.php
  tests/unit-tests/WCGoogleGtagJS.php
  woocommerce-google-analytics-integration.php
Labels: changelog: update

#321 Add upgrade notice if property ID starts with "UA"
  includes/class-wc-google-analytics.php
Labels: type: enhancement, changelog: add
