Repository woocommerce/woocommerce-google-analytics-integration, pull requests merged in 2023-09, with the labels that each got.

#298 Fix Add To Cart and Impression events when using Blocks
  includes/class-wc-google-analytics.php
  includes/class-wc-google-gtag-js.php
Labels: type: bug, changelog: fix

#300 Refactor products tracking for clicks and impression
  includes/class-wc-abstract-google-analytics-js.php
  includes/class-wc-google-analytics-js.php
  includes/class-wc-google-analytics.php
  includes/class-wc-google-gtag-js.php
  tests/unit-tests/ListingClick.php
  tests/unit-tests/ListingImpression.php
Labels: type: bug, changelog: fix

#305 Add documentation link with UTM parameters
  woocommerce-google-analytics-integration.php
Labels: changelog: tweak

#303 Add section to privacy policy guide
  includes/class-wc-google-analytics.php
Labels: type: enhancement, changelog: add
