Repository woocommerce/woocommerce-google-analytics-integration, pull requests merged in 2024-03, with the labels that each got.

#360 Remove options remapping, use settings directly.
  includes/class-wc-abstract-google-analytics-js.php
  includes/class-wc-google-analytics.php
  includes/class-wc-google-gtag-js.php
Labels: changelog: dev

#361 Implement consent mode v0
  README.md
  assets/js/src/config.js
  assets/js/src/tracker/index.js
Labels: type: enhancement, changelog: add

#364 Allow more precise consent mode customizations
  README.md
  assets/js/src/config.js
  assets/js/src/tracker/index.js
  includes/class-wc-google-gtag-js.php
Labels: changelog: none

#365 Prevent tracking admins or order multiple times and additional adjustments
  assets/js/src/tracker/data-formatting.js
  assets/js/src/tracker/index.js
  includes/class-wc-abstract-google-analytics-js.php
  includes/class-wc-google-analytics.php
  includes/class-wc-google-gtag-js.php
Labels: type: bug, changelog: fix

#369 Update contributors lists
  readme.txt
Labels: changelog: update

#373 Update assets and readme for 2.0
  readme.txt
  woocommerce-google-analytics-integration.php
  wordpress_org_assets/screenshot-1.png
Labels: changelog: update

#372 Fix formatting product when variation has no attributes
  includes/class-wc-abstract-google-analytics-js.php
Labels: type: bug, changelog: fix

#380 Format price for purchase event
  assets/js/src/tracker/data-formatting.js
  includes/class-wc-abstract-google-analytics-js.php
Labels: type: bug, changelog: fix

#385 Add E2E testing to track events across all page types
  .github/workflows/e2e-tests.yml
  .gitignore
  .wp-env.json
  README.md
  package-lock.json
  package.json
  phpcs.xml.dist
  tests/e2e/bin/test-env-setup.sh
  tests/e2e/config/default.json
  tests/e2e/config/playwright.config.js
  tests/e2e/config/wp-cli.yml
  tests/e2e/global-setup.js
  tests/e2e/specs/gtag-events/blocks-pages.test.js
  tests/e2e/specs/gtag-events/classic-pages.test.js
  tests/e2e/specs/integration-settings.test.js
  tests/e2e/specs/js-scripts/admin-user.test.js
  tests/e2e/specs/js-scripts/customer-logged-in.test.js
  tests/e2e/specs/js-scripts/guest.test.js
  tests/e2e/test-data/test-data.php
  tests/e2e/test-snippets/test-snippets.php
  tests/e2e/utils/api.js
  tests/e2e/utils/constants.js
  tests/e2e/utils/create-page.js
  tests/e2e/utils/customer.js
  tests/e2e/utils/fixtures/product-collection.fixture.json
  tests/e2e/utils/fixtures/products.fixture.json
  tests/e2e/utils/track-event.js
Labels: changelog: dev

#376 Remove unused fallback and undefined variable.
  includes/class-wc-abstract-google-analytics-js.php
Labels: changelog: tweak

#388 Track purchase transaction ID
  assets/js/src/tracker/data-formatting.js
  includes/class-wc-abstract-google-analytics-js.php
  tests/e2e/specs/gtag-events/classic-pages.test.js
  tests/e2e/utils/customer.js
Labels: type: bug, changelog: fix

#386 Handle AJAX add to cart for simple products
  assets/js/src/integrations/classic.js
  assets/js/src/tracker/data-formatting.js
Labels: type: bug, changelog: fix

#397 E2E tests for the All Products block
  tests/e2e/specs/gtag-events/blocks-pages.test.js
  tests/e2e/utils/create-page.js
  tests/e2e/utils/fixtures/all-products.fixture.json
Labels: changelog: dev

#402 Add require plugins header
  woocommerce-google-analytics-integration.php
Labels: changelog: tweak

#375 Remove unused function from formatters
  assets/js/src/tracker/data-formatting.js
Labels: changelog: dev

#406 Add QIT workflow
  .github/workflows/build.yml
  .github/workflows/run-qit.yml
Labels: changelog: dev

#400 Fix warning after plugin install using wp-cli
  includes/class-wc-google-analytics.php
Labels: changelog: fix

#404 Register `woocommerce-google-analytics-integration` script ASAP
  includes/class-wc-google-gtag-js.php
  tests/e2e/specs/js-scripts/inline-data.test.js
  tests/e2e/test-snippets/test-snippets.php
Labels: type: bug, changelog: fix
