Repository woocommerce/woocommerce-google-analytics-integration, pull requests merged in 2024-05, with the labels that each got.

#418 Avoid running untrusted input as shell commands in the GitHub Actions
  .github/workflows/php-hook-documentation.yml
Labels: changelog: dev

#420 Avoid running malicious inputs as shell commands in the GitHub Actions
  .github/workflows/e2e-tests.yml
  .github/workflows/php-unit-tests.yml
Labels: changelog: dev

#419 Apply discounts to the ecommerce event if available
  assets/js/src/utils/index.js
  includes/class-wc-abstract-google-analytics-js.php
Labels: type: bug, changelog: fix

#421 Fix incorrect quantity when product is already in cart
  assets/js/src/utils/index.js
  includes/class-wc-abstract-google-analytics-js.php
  tests/e2e/specs/gtag-events/blocks-pages.test.js
  tests/e2e/specs/gtag-events/classic-pages.test.js
Labels: type: bug, changelog: fix

#423 Upgrade the workflows in GitHub Actions to use Node.js v20
  .github/workflows/backlog-automation.yml
  .github/workflows/branch-labels.yml
  .github/workflows/build.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/js-linting.yml
  .github/workflows/php-coding-standards-diff.yml
  .github/workflows/php-hook-documentation.yml
  .github/workflows/php-unit-tests.yml
  .github/workflows/prepare-release.yml
  .github/workflows/run-qit.yml
Labels: changelog: dev

#425 Add integration with WP Consent API
  assets/js/src/index.js
  assets/js/src/integrations/wp-consent-api.js
  includes/class-wc-google-analytics.php
  includes/class-wc-google-gtag-js.php
Labels: type: enhancement, changelog: add
