Repository woocommerce/woocommerce-google-analytics-integration, pull requests merged in 2024-08, with the labels that each got.

#453 Update `#billing-state` locator to fix failing E2E test
  tests/e2e/utils/customer.js
Labels: type: bug, changelog: fix

#454 Fix `#billing-state` option select in e2e tests
  tests/e2e/utils/customer.js
Labels: type: bug, changelog: fix, changelog: none

#457 Make the value entering of the billing state field in e2e test compatible with WC < 9.2
  tests/e2e/utils/customer.js
Labels: changelog: dev
