Repository woocommerce/woocommerce-google-analytics-integration, pull requests merged in 2024-06, with the labels that each got.

#429 Add E2E tests for the WP Consent API integration
  tests/e2e/bin/test-env-setup.sh
  tests/e2e/specs/js-scripts/wp-consent-api.test.js
  tests/e2e/test-snippets/test-snippets.php
Labels: changelog: none

#426 Mention the WP Consent API integration in the README
  README.md
Labels: type: enhancement, changelog: add

#430 Add E2E tests for denying via WP Consent API
  tests/e2e/specs/js-scripts/wp-consent-api.test.js
Labels: type: enhancement, changelog: add

#435 Return empty array if WC_Cart is not yet instantiated
  includes/class-wc-abstract-google-analytics-js.php
Labels: changelog: fix, changelog: tweak

#440 [Revert] Update docs domain name to Woo.com
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  README.md
  includes/class-wc-google-analytics.php
  readme.txt
  woocommerce-google-analytics-integration.php
Labels: changelog: tweak

#438 Do not replace another `added_to_cart` vanilla handler if there is one
  assets/js/src/integrations/classic.js
Labels: type: bug, changelog: fix

#439 Add dedicated integration with Product Bundles
  assets/js/src/utils/index.js
  includes/class-wc-abstract-google-analytics-js.php
Labels: type: bug, changelog: fix

#443 Add checks and explicit errors when cart buttons are missing data
  assets/js/src/integrations/classic.js
Labels: changelog: tweak

#445 Upgrade to use Node.js 20 and bump npm dependencies
  .nvmrc
  package-lock.json
  package.json
Labels: changelog: dev
